name: Sunfish CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Upload firmware to Google Drive
    runs-on: ubuntu-latest
    container: ardupilot/ardupilot-dev-chibios:v0.1.3
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        run: |
          NOW=$(date -u +"%F-%T")
          echo "timestamp=${NOW}" >> $GITHUB_OUTPUT
      - name: ccache cache files
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{github.workflow}}-ccache-${{steps.ccache_cache_timestamp.outputs.timestamp}}
          restore-keys: ${{github.workflow}}-ccache-${{steps.ccache_cache_timestamp.outputs.timestamp}}  # restore ccache from either previous build on this branch or on master
      - name: setup ccache
        run: |
          . .github/workflows/ccache.env
      - name: Build Sunfish firmware
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          PATH="/usr/lib/ccache:/opt/gcc-arm-none-eabi-10/bin:$PATH"
          PATH="/github/home/.local/bin:$PATH"
          make sunfish
          ccache -s
      - name: Upload binaries to Google Drive
        uses: adityak74/google-drive-upload-git-action@v0.3
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          filename: build/sunfish/*
